"""empty message

Revision ID: d8054097d213
Revises: 
Create Date: 2021-10-28 17:01:16.002000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8054097d213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courseName', sa.String(), nullable=True),
    sa.Column('courseDescription', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requestFrom', sa.Integer(), nullable=True),
    sa.Column('requestToCourse', sa.Integer(), nullable=True),
    sa.Column('requestToLector', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requestFrom'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requestToCourse'], ['course.id'], ),
    sa.ForeignKeyConstraint(['requestToLector'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('users')
    op.drop_table('course')
    # ### end Alembic commands ###
